name: 'Terraform remote state'
description: 'Get a variable from a terraform remote workspace'
inputs:
  organization:
    description: 'The organization that owns the workspace'
    required: true
  workspace:
    description: 'The name of the workspace'
    required: true
  token:
    description: 'The access token for accessing Terraform cloud'
    required: true
  name:
    description: 'The name of the output variable to get. If omitted, returns all outputs.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.organization }}
    - ${{ inputs.workspace }}
    - ${{ inputs.token }}
    - ${{ inputs.name }}
