name: 'Terraform remote state'
description: 'Get a variable from a terraform remote workspace'
inputs:
  role_arn:
    description: 'The account arn of the account where the terraform state lives'
    required: true
  bucket:
    description: 'The bucket name of the bucket where the terraform state lives'
    required: true
  bucket_key:
    description: 'The bucket name of the terraform states path within the bucket'
    required: true
  region:
    description: 'The AWS region where the terraform state lives eg: (eu-west-2)'
    required: true
  dynamodb_table_name:
    description: 'The dynamodb table name where the terraform lock lives'
    required: true
  name:
    description: 'The name of the output variable to get. If omitted, returns all outputs.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.role_arn }}
    - ${{ inputs.bucket }}
    - ${{ inputs.bucket_key }}
    - ${{ inputs.region }}
    - ${{ inputs.dynamodb_table_name }}
    - ${{ inputs.name }}
